<?php

namespace App\Console\Commands;

use BackedEnum;
use Illuminate\Console\Command;
use ReflectionEnum;
use Symfony\Component\Finder\Finder;

/**
 * Emit the enum vocabulary as TypeScript, so the two halves of the app agree on
 * what a status is.
 *
 * Sixteen enums back every status column on the server, and the frontend has
 * been repeating their values as bare string literals — `['approved',
 * 'completed'].includes(...)`, `status === 'pending'`, a `statusChips` array.
 * Nothing ties those spellings to the PHP they mirror, so renaming a case is a
 * server-side change that silently stops a filter matching in the browser.
 *
 * Generated rather than hand-written for the obvious reason: a hand-written copy
 * is a third place to forget. `--check` is the CI form — it regenerates into a
 * buffer and fails if the committed file has drifted, which turns "somebody
 * forgot to re-run this" into a red build instead of a stale type.
 */
class GenerateTypeScriptTypes extends Command
{
    protected $signature = 'tims:types {--check : Fail if the committed file is out of date instead of writing it}';

    protected $description = 'Generate resources/js/types/enums.ts from App\\Enums';

    private const OUTPUT = 'resources/js/types/enums.ts';

    public function handle(): int
    {
        $enums = $this->enums();

        if ($enums === []) {
            $this->error('No backed enums found in app/Enums.');

            return self::FAILURE;
        }

        $generated = $this->render($enums);
        $path = base_path(self::OUTPUT);

        if ($this->option('check')) {
            $current = is_file($path) ? file_get_contents($path) : '';

            if ($current === $generated) {
                $this->info(self::OUTPUT.' is up to date ('.count($enums).' enums).');

                return self::SUCCESS;
            }

            $this->error(self::OUTPUT.' is out of date. Run `php artisan tims:types`.');

            return self::FAILURE;
        }

        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0777, true);
        }

        file_put_contents($path, $generated);
        $this->info('Wrote '.self::OUTPUT.' ('.count($enums).' enums).');

        return self::SUCCESS;
    }

    /**
     * Every backed enum under app/Enums, as [short name => [case => value]].
     *
     * @return array<string, array<string, string|int>>
     */
    private function enums(): array
    {
        $found = [];

        $files = (new Finder)->files()->in(app_path('Enums'))->name('*.php')->sortByName();

        foreach ($files as $file) {
            $class = 'App\\Enums\\'.$file->getBasename('.php');

            if (! enum_exists($class)) {
                continue;
            }

            $reflection = new ReflectionEnum($class);

            // Pure enums have no wire representation, so there is nothing for
            // the browser to compare against.
            if (! $reflection->isBacked()) {
                continue;
            }

            $cases = [];

            foreach ($class::cases() as $case) {
                // isBacked() above already settles this, but it settles it for
                // a reader rather than for the analyser: `$class` is a string
                // here, so cases() is only known to yield UnitEnum, which has
                // no ->value. Narrowing on the instance is what makes the read
                // safe rather than merely believed to be safe.
                if (! $case instanceof BackedEnum) {
                    continue;
                }

                $cases[$case->name] = $case->value;
            }

            $found[$file->getBasename('.php')] = $cases;
        }

        return $found;
    }

    /**
     * @param  array<string, array<string, string|int>>  $enums
     */
    private function render(array $enums): string
    {
        $lines = [
            '/**',
            ' * Generated by `php artisan tims:types` — do not edit by hand.',
            ' *',
            ' * The values of every backed enum in app/Enums, so a status compared in the',
            ' * browser is compared against the same spelling the server stores. Editing',
            ' * this file is pointless: CI runs `tims:types --check` and will fail on any',
            ' * difference between it and the PHP.',
            ' *',
            ' * A real module rather than a .d.ts, deliberately. The arrays are what a',
            ' * component actually needs to build a filter row or iterate statuses, and a',
            ' * declaration file would promise values that do not exist at runtime — an',
            ' * import that type-checks and then reads undefined in the browser. Declaring',
            ' * the array `as const` and deriving the union from it also means the two can',
            ' * never list different cases.',
            ' */',
            '',
        ];

        foreach ($enums as $name => $cases) {
            $values = array_map(
                fn ($value) => is_int($value) ? (string) $value : "'".$value."'",
                $cases
            );

            $lines[] = 'export const '.lcfirst($name).'Values = [';

            foreach ($values as $value) {
                $lines[] = '    '.$value.',';
            }

            $lines[] = '] as const;';
            $lines[] = '';
            $lines[] = 'export type '.$name.' = (typeof '.lcfirst($name).'Values)[number];';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }
}
