<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Events\Verified;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response;

/**
 * The self-service email verification flow.
 *
 * Routes in the shape Laravel's own mustVerifyEmail flow expects so the signed
 * URL generated by the notification matches the framework's contract, but the
 * rendering is Inertia and the copy is this office's.
 */
class EmailVerificationController extends Controller
{
    /**
     * Said in one place because two of them say it: this controller when the
     * "continue" button is pressed too early, and EnsureEmailIsVerified when
     * any gated route is reached the same way.
     */
    public const NOT_YET_VERIFIED = 'That address is not verified yet. Open the link in the email we sent, or resend it below.';

    /**
     * The "check your inbox" screen shown to an unverified, signed-in user.
     */
    public function notice(Request $request): Response
    {
        return Inertia::render('Auth/VerifyEmail', [
            'email' => $request->user()->email,
        ]);
    }

    /**
     * The notice page's "I've already verified — continue" button.
     *
     * The emailed link is usually opened in another tab, another browser, or
     * on a phone, so this page has no way of knowing it was clicked — the
     * button exists to go and ask. It used to point straight at the dashboard,
     * which asked the *profile* gate first because that middleware is listed
     * ahead of the verification one: an unverified participant who had not
     * finished their profile — which is every participant at this point in the
     * sequence — was sent into the profile form as though the answer had been
     * yes. Asking the one question the button is about, before any of that,
     * is the whole job.
     */
    public function check(Request $request): RedirectResponse
    {
        $user = $request->user();

        // Staff are exempt here for the same reason EnsureEmailIsVerified
        // exempts them: they are not asked to verify a self-service address,
        // and a button that answered differently from the gate behind it would
        // be its own bug.
        if (! $user->role->isStaff() && ! $user->hasVerifiedEmail()) {
            return redirect()->route('verification.notice')->with('error', self::NOT_YET_VERIFIED);
        }

        return redirect()->route('dashboard');
    }

    /**
     * The link from the email: marks the address verified and lets the user in.
     */
    public function verify(Request $request, int $id, string $hash): RedirectResponse
    {
        $user = User::findOrFail($id);

        // A signed URL guarantees who, but the hash still guards against a
        // stale id slipping through — same check Laravel's own guard does.
        abort_unless(hash_equals(sha1($user->getEmailForVerification()), (string) $hash), 403);

        if ($user->markEmailAsVerified()) {
            event(new Verified($user));
        }

        if ($request->user()?->is($user)) {
            return redirect()->intended(route('dashboard'))->with('success', 'Your email address has been verified.');
        }

        return redirect()->route('login')->with('status', 'Your email address has been verified — you can now sign in.');
    }

    /**
     * Resend for the signed-in user, from the notice page or the gate form.
     */
    public function send(Request $request): RedirectResponse
    {
        if ($request->user()->hasVerifiedEmail()) {
            return redirect()->intended(route('dashboard'));
        }

        $request->user()->sendEmailVerificationNotification();

        return back()->with('status', 'A new verification link has been sent to your email address.');
    }

    /**
     * Resend from the login screen, where the visitor is not signed in.
     *
     * Rate limited on purpose: sending on demand to an address that belongs to
     * nobody is harmless, but it must not be exploitable as an email flooder.
     */
    public function resend(Request $request): RedirectResponse
    {
        $credentials = $request->validate([
            'email' => ['required', 'string', 'email'],
        ]);

        $user = User::where('email', $credentials['email'])
            ->whereNull('email_verified_at')
            ->first();

        // Matching the blocked-login copy in LoginController, so a visitor who
        // tries to re-send to an address that is now verified gets told so.
        if (! $user) {
            throw ValidationException::withMessages([
                'email' => 'There is no pending verification for that email address.',
            ]);
        }

        $user->sendEmailVerificationNotification();

        return back()->with('status', 'A new verification link has been sent to your email address.');
    }
}
