<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Events\Verified;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response;

/**
 * The self-service email verification flow.
 *
 * Routes in the shape Laravel's own mustVerifyEmail flow expects so the signed
 * URL generated by the notification matches the framework's contract, but the
 * rendering is Inertia and the copy is this office's.
 */
class EmailVerificationController extends Controller
{
    /**
     * The "check your inbox" screen shown to an unverified, signed-in user.
     */
    public function notice(Request $request): Response
    {
        return Inertia::render('Auth/VerifyEmail', [
            'email' => $request->user()->email,
        ]);
    }

    /**
     * The link from the email: marks the address verified and lets the user in.
     */
    public function verify(Request $request, int $id, string $hash): RedirectResponse
    {
        $user = User::findOrFail($id);

        // A signed URL guarantees who, but the hash still guards against a
        // stale id slipping through — same check Laravel's own guard does.
        abort_unless(hash_equals(sha1($user->getEmailForVerification()), (string) $hash), 403);

        if ($user->markEmailAsVerified()) {
            event(new Verified($user));
        }

        if ($request->user()?->is($user)) {
            return redirect()->intended(route('dashboard'))->with('success', 'Your email address has been verified.');
        }

        return redirect()->route('login')->with('status', 'Your email address has been verified — you can now sign in.');
    }

    /**
     * Resend for the signed-in user, from the notice page or the gate form.
     */
    public function send(Request $request): RedirectResponse
    {
        if ($request->user()->hasVerifiedEmail()) {
            return redirect()->intended(route('dashboard'));
        }

        $request->user()->sendEmailVerificationNotification();

        return back()->with('status', 'A new verification link has been sent to your email address.');
    }

    /**
     * Resend from the login screen, where the visitor is not signed in.
     *
     * Rate limited on purpose: sending on demand to an address that belongs to
     * nobody is harmless, but it must not be exploitable as an email flooder.
     */
    public function resend(Request $request): RedirectResponse
    {
        $credentials = $request->validate([
            'email' => ['required', 'string', 'email'],
        ]);

        $user = User::where('email', $credentials['email'])
            ->whereNull('email_verified_at')
            ->first();

        // Matching the blocked-login copy in LoginController, so a visitor who
        // tries to re-send to an address that is now verified gets told so.
        if (! $user) {
            throw ValidationException::withMessages([
                'email' => 'There is no pending verification for that email address.',
            ]);
        }

        $user->sendEmailVerificationNotification();

        return back()->with('status', 'A new verification link has been sent to your email address.');
    }
}
