/**
 * Generated by `php artisan tims:types` — do not edit by hand.
 *
 * The values of every backed enum in app/Enums, so a status compared in the
 * browser is compared against the same spelling the server stores. Editing
 * this file is pointless: CI runs `tims:types --check` and will fail on any
 * difference between it and the PHP.
 *
 * A real module rather than a .d.ts, deliberately. The arrays are what a
 * component actually needs to build a filter row or iterate statuses, and a
 * declaration file would promise values that do not exist at runtime — an
 * import that type-checks and then reads undefined in the browser. Declaring
 * the array `as const` and deriving the union from it also means the two can
 * never list different cases.
 */

export const agencyDocumentKindValues = [
    'request_letter',
    'response_letter',
    'blank_confirmation_form',
    'rejection_letter',
    'signed_confirmation_form',
    'certificate_of_duties',
    'attendance_sheet',
    'attendance_list',
    'proof_of_payment',
] as const;

export type AgencyDocumentKind = (typeof agencyDocumentKindValues)[number];

export const agencyRequestStatusValues = [
    'pending',
    'under_review',
    'requirements_sent',
    'confirmed',
    'completed',
    'rejected',
    'cancelled',
] as const;

export type AgencyRequestStatus = (typeof agencyRequestStatusValues)[number];

export const attendanceStatusValues = [
    'present',
    'late',
    'absent',
    'excused',
] as const;

export type AttendanceStatus = (typeof attendanceStatusValues)[number];

export const chargeToValues = [
    'personal',
    'agency',
] as const;

export type ChargeTo = (typeof chargeToValues)[number];

export const curriculumValues = [
    'Technical',
    'Leadership and Management',
    'Foundation',
] as const;

export type Curriculum = (typeof curriculumValues)[number];

export const evaluationRatingValues = [
    1,
    2,
    3,
    4,
    5,
] as const;

export type EvaluationRating = (typeof evaluationRatingValues)[number];

export const paymentMethodValues = [
    'cash',
    'check',
    'online',
    'credit_card',
    'lddap',
    'promissory',
    'official_receipt',
] as const;

export type PaymentMethod = (typeof paymentMethodValues)[number];

export const paymentStatusValues = [
    'pending',
    'verified',
    'rejected',
] as const;

export type PaymentStatus = (typeof paymentStatusValues)[number];

export const physicalOrRequestStatusValues = [
    'request_submitted',
    'payment_verification_pending',
    'payment_verified',
    'preparing',
    'ready_for_shipment',
    'shipped',
    'delivered',
    'rejected',
] as const;

export type PhysicalOrRequestStatus = (typeof physicalOrRequestStatusValues)[number];

export const refundStatusValues = [
    'for_review',
    'processing',
    'forwarded_to_msd',
    'for_release',
    'refunded',
    'rejected',
] as const;

export type RefundStatus = (typeof refundStatusValues)[number];

export const registrationStatusValues = [
    'pending',
    'approved',
    'waitlisted',
    'rejected',
    'cancelled',
    'completed',
] as const;

export type RegistrationStatus = (typeof registrationStatusValues)[number];

export const requestStatusValues = [
    'pending',
    'approved',
    'rejected',
] as const;

export type RequestStatus = (typeof requestStatusValues)[number];

export const roleValues = [
    'participant',
    'field-office',
    'collecting-officer',
    'admin',
    'management',
    'superadmin',
] as const;

export type Role = (typeof roleValues)[number];

export const supervisoryDocumentStatusValues = [
    'required',
    'submitted',
    'verified',
    'rejected',
] as const;

export type SupervisoryDocumentStatus = (typeof supervisoryDocumentStatusValues)[number];

export const trainingLevelValues = [
    'foundational',
    'intermediate',
    'advanced',
] as const;

export type TrainingLevel = (typeof trainingLevelValues)[number];

export const trainingModeValues = [
    'face_to_face',
    'online',
    'hybrid',
] as const;

export type TrainingMode = (typeof trainingModeValues)[number];

export const trainingStatusValues = [
    'draft',
    'published',
    'closed',
    'completed',
    'cancelled',
] as const;

export type TrainingStatus = (typeof trainingStatusValues)[number];
