<script setup>
import { Head, Link } from '@inertiajs/vue3';
import LegalLayout from '@/Layouts/LegalLayout.vue';
</script>

<template>
    <Head title="Terms of Service" />

    <LegalLayout title="Terms of Service" updated="12 August 2026">
        <section>
            <h2 class="mb-2 text-lg font-semibold text-csc-blue">1. Acceptance of Terms</h2>
            <p>
                By accessing or using the Training Information Management System (TIMS) of the Civil Service Commission,
                you agree to these Terms of Service. If you do not agree, do not use the system.
            </p>
        </section>

        <section>
            <h2 class="mb-2 text-lg font-semibold text-csc-blue">2. Accounts</h2>
            <p>
                TIMS accounts are provisioned by the Commission or by your agency's designated coordinator. Accounts are
                personal and non-transferable. You are responsible for all activity carried out under your account and
                must notify the Commission promptly of any suspected unauthorised use.
            </p>
        </section>

        <section>
            <h2 class="mb-2 text-lg font-semibold text-csc-blue">3. Acceptable Use</h2>
            <ul class="list-inside list-disc space-y-1 text-csc-ink/80">
                <li>Submit accurate and complete information in all nominations and records.</li>
                <li>Do not share credentials or allow another person to use your account.</li>
                <li>
                    Do not attempt to access data, accounts, or system functions beyond those granted to your role.
                </li>
                <li>Do not disrupt, probe, or attempt to circumvent the security of the service.</li>
            </ul>
        </section>

        <section>
            <h2 class="mb-2 text-lg font-semibold text-csc-blue">4. Accuracy of Records</h2>
            <p>
                Training records, certificates, and reports generated by TIMS are official documents of the Commission.
                Submitting false information may result in withdrawal of certification and in administrative liability
                under civil service rules.
            </p>
        </section>

        <section>
            <h2 class="mb-2 text-lg font-semibold text-csc-blue">5. Availability</h2>
            <p>
                The Commission aims to keep TIMS available at all times but does not guarantee uninterrupted service.
                Access may be suspended for maintenance, security, or operational reasons without prior notice.
            </p>
        </section>

        <section>
            <h2 class="mb-2 text-lg font-semibold text-csc-blue">6. Intellectual Property</h2>
            <p>
                All content, seals, and marks displayed on this site are the property of the Civil Service Commission or
                the Republic of the Philippines and may not be reproduced without authorisation.
            </p>
        </section>

        <section>
            <h2 class="mb-2 text-lg font-semibold text-csc-blue">7. Suspension and Termination</h2>
            <p>
                The Commission may suspend or terminate access for any breach of these Terms, for security reasons, or
                when a user leaves the service of their agency.
            </p>
        </section>

        <section>
            <h2 class="mb-2 text-lg font-semibold text-csc-blue">8. Changes to These Terms</h2>
            <p>
                These Terms may be updated from time to time. Continued use of TIMS after an update constitutes
                acceptance of the revised Terms.
            </p>
        </section>

        <p class="border-t border-csc-line pt-6 text-xs text-csc-ink/60">
            See also our
            <Link href="/privacy-policy" class="font-medium text-csc-blue hover:underline">Privacy Policy</Link>.
        </p>
    </LegalLayout>
</template>
